export const letters = [
  { value: "Q", isInWord: false, inCorrectSpot: false },
  { value: "W", isInWord: false, inCorrectSpot: false },
  { value: "E", isInWord: false, inCorrectSpot: false },
  { value: "R", isInWord: false, inCorrectSpot: false },
  { value: "T", isInWord: false, inCorrectSpot: false },
  { value: "Y", isInWord: false, inCorrectSpot: false },
  { value: "U", isInWord: false, inCorrectSpot: false },
  { value: "I", isInWord: false, inCorrectSpot: false },
  { value: "O", isInWord: false, inCorrectSpot: false },
  { value: "P", isInWord: false, inCorrectSpot: false },
  { value: "A", isInWord: false, inCorrectSpot: false },
  { value: "S", isInWord: false, inCorrectSpot: false },
  { value: "D", isInWord: false, inCorrectSpot: false },
  { value: "F", isInWord: false, inCorrectSpot: false },
  { value: "G", isInWord: false, inCorrectSpot: false },
  { value: "H", isInWord: false, inCorrectSpot: false },
  { value: "J", isInWord: false, inCorrectSpot: false },
  { value: "K", isInWord: false, inCorrectSpot: false },
  { value: "L", isInWord: false, inCorrectSpot: false },
  { value: 'enter' },
  { value: "Z", isInWord: false, inCorrectSpot: false },
  { value: "X", isInWord: false, inCorrectSpot: false },
  { value: "C", isInWord: false, inCorrectSpot: false },
  { value: "V", isInWord: false, inCorrectSpot: false },
  { value: "B", isInWord: false, inCorrectSpot: false },
  { value: "N", isInWord: false, inCorrectSpot: false },
  { value: "M", isInWord: false, inCorrectSpot: false },
  { value: 'delete' }
];